// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateText('text', { text: 'SlimTimer Widget' });
    CreateText('text1', { text: 'by Piotr Banasik' });
    CreateText('version', { text: '0.6' });
}
window.addEventListener('load', setupParts, false);
