// This file was generated by Dashcode from Apple Computer, Inc.
// You may edit this file to customize your Dashboard widget.

function load()
{
	setupParts();
}

function initialize() {
	box = document.getElementById("box")
	box.style.visibility = ""

	var slimTimerFrame = document.createElement("iframe");
	slimTimerFrame.setAttribute("id", "slimTimerFrame");
	slimTimerFrame.setAttribute("width", "100%");
	slimTimerFrame.setAttribute("height", "100%");
	slimTimerFrame.setAttribute("frameBorder", "0");

	box.appendChild(slimTimerFrame);

	slimTimerFrame = document.getElementById("slimTimerFrame")
	slimTimerFrame.setAttribute("src", "http://www.slimtimer.com/client")
}

function remove()
{
	// your widget has just been removed from the layer
	// remove any preferences as needed
	// widget.setPreferenceForKey(null, createInstancePreferenceKey("your-key"));
}

function hide()
{
	// your widget has just been hidden stop any timers to
	// prevent cpu usage
}

function show()
{
	initialize();

	// your widget has just been shown.  restart any timers
	// and adjust your interface as needed
}

function showBack(event)
{
	// your widget needs to show the back

	var front = document.getElementById("front");
	var back = document.getElementById("back");

	if (window.widget)
		widget.prepareForTransition("ToBack");

	front.style.display="none";
	back.style.display="block";
	
	if (window.widget)
		setTimeout('widget.performTransition();', 0);
}

function showFront(event)
{
	// your widget needs to show the front

	var front = document.getElementById("front");
	var back = document.getElementById("back");

	if (window.widget)
		widget.prepareForTransition("ToFront");

	front.style.display="block";
	back.style.display="none";
	
	if (window.widget)
		setTimeout('widget.performTransition();', 0);
}

if (window.widget)
{
	widget.onremove = remove;
	widget.onhide = hide;
	widget.onshow = show;
}
